arangodb:
  DB_end_point: createDB
  DB_service_host: localhost
  DB_service_name: createDB
  DB_service_port: 8529
  arangodb_replication_factor: null
  conn_protocol: http
  dbName: umbocv_ap_demo
  password: umbocv_ap_demo
  username: umbocv_ap_demo
mlgraph:
  graphname: enterprise_ml_graph
