FROM arangodb:3.4
FROM continuumio/miniconda3 
MAINTAINER Joerg Schad <info@arangodb.com>
ENV GIT_PYTHON_REFRESH=quiet
RUN apt-get update
RUN apt-get install -y python-pip
RUN pip install mlflow hyperopt sklearn2 jsonpickle python-arango==4.4.0
RUN pip install -i https://test.pypi.org/simple/ arangopipe
RUN mkdir -p /workspace
RUN pip install jupyter
RUN pip install matplotlib
RUN pip install PyYAML==5.1.1
RUN conda install pytorch torchvision cudatoolkit=10.0 -c pytorch 
#RUN git clone git@github.com:arangoml/arangopipe.git /workspace
WORKDIR /
COPY --from=0 / .
WORKDIR /workspace/experiments
COPY tests/AQL/ examples/AQL/
COPY tests/covariate_shift/ examples/covariate_shift/
COPY tests/hyperopt/ examples/hyperopt/
COPY tests/mlflow/ examples/mlflow/
COPY tests/test_data_generator/ examples/test_data_generator/
COPY tests/pytorch/ examples/pytorch/
COPY arangopipe_examples.ipynb .
ENV PYTHONPATH=`pwd`:$PYTHONPATH
RUN jupyter notebook --generate-config --allow-root
RUN echo "c.NotebookApp.password = u'sha1:6a3f528eec40:6e896b6e4828f525a6e20e5411cd1c8075d68619'" >> /root/.jupyter/jupyter_notebook_config.py
EXPOSE 8888 8529
COPY startup_commands.sh /workspace/scripts/startup_commands.sh
RUN ["chmod", "+x", "/workspace/scripts/startup_commands.sh"]
ENTRYPOINT ["/workspace/scripts/startup_commands.sh"]

