FROM arangodb:3.4
# This image uses two base images arangodb (above) and tensorflow (below)

FROM node:8.7.0-alpine AS frontend
RUN mkdir -p /arangopipe_frontend
WORKDIR /arangopipe_frontend
COPY arangopipe_frontend/app/package.json /arangopipe_frontend
COPY arangopipe_frontend/app/package-lock.json /arangopipe_frontend
RUN npm install
COPY arangopipe_frontend/app/ /arangopipe_frontend
FROM tensorflow/tensorflow:latest-py3

MAINTAINER Joerg Schad <info@arangodb.com>
ENV GIT_PYTHON_REFRESH=quiet
RUN apt-get update
RUN apt-get install -y python-pip
RUN apt-get install -y python-pip curl
RUN pip install mlflow hyperopt sklearn2 jsonpickle python-arango arangopipe jupyter matplotlib tensorflow-data-validation PyYAML==5.1.1
RUN mkdir -p /workspace

WORKDIR /
COPY --from=0 / .
WORKDIR /workspace/experiments
COPY --from=frontend /arangopipe_frontend .
COPY tests/AQL/ examples/AQL/
COPY tests/covariate_shift/ examples/covariate_shift/
COPY tests/hyperopt/ examples/hyperopt/
COPY tests/mlflow/ examples/mlflow/
COPY tests/test_data_generator/ examples/test_data_generator/
COPY tests/TFX/ examples/TFX/
COPY arangopipe_examples.ipynb .
ENV PYTHONPATH=`pwd`:$PYTHONPATH
RUN jupyter notebook --generate-config --allow-root
RUN echo "c.NotebookApp.password = u'sha1:6a3f528eec40:6e896b6e4828f525a6e20e5411cd1c8075d68619'" >> /root/.jupyter/jupyter_notebook_config.py

EXPOSE 8888 8529 3000

COPY startup_commands.sh /workspace/experiments/startup_commands.sh
RUN ["chmod", "+x", "/workspace/experiments/startup_commands.sh"]
ENTRYPOINT ["/workspace/experiments/startup_commands.sh"]
