FROM python:3.7
RUN pip install jsonpickle python-arango jupyter sklearn2 PyYAML==5.1.1
RUN pip install -i https://test.pypi.org/simple/ arangopipe
WORKDIR /
COPY tests/prod_docker/test_installation.py tests/



