export const COMMON = {
  START_LOADING: 'START_LOADING',
  END_LOADING: 'END_LOADING'
}


export const USER = {
  SIGNED_IN: 'SIGNED_IN',
  SIGNED_OUT: 'SIGNED_OUT'
}

export const DOCUMENT = {
  DOC_ALL: 'DOC_ALL',
  PROCESSED: 'PROCESSED',
  DB_CLEARED: 'DB_CLEARED',
  DOC_DELETED: 'DOC_DELETED',
  DETAIL_INFO: 'DETAIL_INFO',
  GRAPH: 'GRAPH'
}

export const QUERY = {
  QUERY_ALL: 'QUERY_ALL',
  SAVED_QUERY: 'SAVED_QUERY',
  QUERY_RESULT: 'QUERY_RESULT',
  QUERY_EXPLAIN: 'QUERY_EXPLAIN',
  ERROR: 'ERROR',
  CLEAR: 'CLEAR'
}

