arangodb:
  DB_end_point: createDB
  DB_service_host: arangoml.arangodb.cloud
  DB_service_name: createDB
  DB_service_port: 8529
  arangodb_replication_factor: null
  conn_protocol: https
  dbName: MLjlttmbjvrilzr8khg0lni
  password: MLt9r19h8sindhjc1ekjrgb
  username: ML3dkcs4295623ww0c8cr3ym
mlgraph:
  graphname: enterprise_ml_graph
