arangodb:
  DB_end_point: createDB
  DB_service_host: localhost
  DB_service_name: createDB
  DB_service_port: 8529
  arangodb_replication_factor: null
  conn_protocol: http
  dbName: ML881pqplr9vps5p5xfdhizn
  password: MLtvwiapyo74dkg1irl0ztc
  username: MLtwb3i0ws26e3l31ovv0n37
mlgraph:
  graphname: enterprise_ml_graph
