version: '3'
services:
  app:
    build: ./app
    environment:
      - REACT_APP_PORT=3000
    expose: 
      - 3000
    ports:
      - "3000:3000"
    volumes: 
      - ./app/src:/srv/app/arangoml-ui/src
      - ./app/public:/srv/app/arangoml-ui/public

    command: npm run start