name: build
on:
  workflow_dispatch:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
env:
  PACKAGE_DIR: arangopipe
jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./arangopipe/arangopipe
    strategy:
      matrix:
        python: ["3.7", "3.8", "3.9", "3.10"]
    name: Python ${{ matrix.python }}
    steps:
      - uses: actions/checkout@v2
      - name: Setup Python ${{ matrix.python }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}
      - name: Setup pip
        run: python -m pip install --upgrade pip setuptools wheel
      - name: Install packages
        run: pip install -r requirements.txt
